### ISSUE TITLE
Fix command fails at step 2 for a file missing rsID and pval

### ISSUE THREAD

**Issue by carlostellophd** [Kukuster/SSrehab#5]
```Step 2: Validate entries in the formatted GWAS SS file and save the report === number of lines in the file: 28987535 validating entries : 100%|███████████████████████████████████████████████████████████████████████████████████████████| 28987534/28987534 [03:02<00:00, 159012.85it/s] calculating reports: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 28987534/28987534 [01:04<00:00, 446130.26it/s] generating reports found issues: rsID: 28987534/28987534 (100.0%) EAF: 5145971/28987534 (17.75%) SE: 5145971/28987534 (17.75%) beta: 5145971/28987534 (17.75%) pval: 28987534/28987534 (100.0%) Traceback (most recent call last): File "/usr/local/bin/SumStatsRehab", line 11, in <module> load_entry_point('SumStatsRehab==1.2.1', 'console_scripts', 'SumStatsRehab')() File "/usr/local/lib/python3.8/dist-packages/SumStatsRehab-1.2.1-py3.8.egg/SumStatsRehab.py", line 730, in main fix(args.INPUT_GWAS_FILE, args.OUTPUT_FILE, File "/usr/local/lib/python3.8/dist-packages/SumStatsRehab-1.2.1-py3.8.egg/SumStatsRehab.py", line 199, in fix validate_GWASSS_entries( File "/usr/local/lib/python3.8/dist-packages/SumStatsRehab-1.2.1-py3.8.egg/lib/validate_GWASSS_entries.py", line 551, in validate_GWASSS_entries write_report_to_dir(issues_count, REPORT_ABS_DIR) File "/usr/local/lib/python3.8/dist-packages/SumStatsRehab-1.2.1-py3.8.egg/lib/report_utils.py", line 23, in write_report_to_dir with open(os.path.join(REPORT_DIR, INVALID_ENTRIES_REPORT_FILENAME), 'w') as f: PermissionError: [Errno 13] Permission denied: '/home/carlos/ssfiles/Bronchitis-row1722.bgz_input-report/invalid_entries.csv```

**Comment by carlostellophd** [comment]
`=== Step 2: Validate entries in the formatted GWAS SS file and save the report ===
number of lines in the file: 28987535
validating entries : 100%|███████████████████████████████████████████████████████████████████████████████████████████| 28987534/28987534 [03:02<00:00, 159012.85it/s]
calculating reports: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 28987534/28987534 [01:04<00:00, 446130.26it/s]
generating reports
found issues:
    rsID: 28987534/28987534 (100.0%)
    EAF: 5145971/28987534 (17.75%)
    SE: 5145971/28987534 (17.75%)
    beta: 5145971/28987534 (17.75%)
    pval: 28987534/28987534 (100.0%)
Traceback (most recent call last):
  File "/usr/local/bin/SumStatsRehab", line 11, in <module>
    load_entry_point('SumStatsRehab==1.2.1', 'console_scripts', 'SumStatsRehab')()
  File "/usr/local/lib/python3.8/dist-packages/SumStatsRehab-1.2.1-py3.8.egg/SumStatsRehab.py", line 730, in main
    fix(args.INPUT_GWAS_FILE, args.OUTPUT_FILE,
  File "/usr/local/lib/python3.8/dist-packages/SumStatsRehab-1.2.1-py3.8.egg/SumStatsRehab.py", line 199, in fix
    validate_GWASSS_entries(
  File "/usr/local/lib/python3.8/dist-packages/SumStatsRehab-1.2.1-py3.8.egg/lib/validate_GWASSS_entries.py", line 551, in validate_GWASSS_entries
    write_report_to_dir(issues_count, REPORT_ABS_DIR)
  File "/usr/local/lib/python3.8/dist-packages/SumStatsRehab-1.2.1-py3.8.egg/lib/report_utils.py", line 23, in write_report_to_dir
    with open(os.path.join(REPORT_DIR, INVALID_ENTRIES_REPORT_FILENAME), 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/carlos/ssfiles/Bronchitis-row1722.bgz_input-report/invalid_entries.csv'`

**Comment by Kukuster** [comment]
solved on the user's side
