### ISSUE TITLE
Unable to install:Failed to build scipy

### ISSUE THREAD

**Issue by ty-hei** [Kukuster/SSrehab#6]
After `pip install -r requirements.txt`

ERROR: Failed building wheel for scipy
Failed to build scipy
ERROR: Could not build wheels for scipy, which is required to install pyproject.toml-based projects

Detail: a new conda env based on python3
Tried `pip install scipy==1.6.1`, same problem occored, I searched and have no idea to slove this problem. 
and I tried `pip install pyproject.toml`, it seems have no thing to do with this problem

**Comment by Kukuster** [comment]
could not reproduce the issue. This _may_ be fixed by updating scipy.

We will be making an update. Until that, follow [the workaround](https://github.com/Kukuster/SumStatsRehab/issues/8#issuecomment-2073598557) (steps not related to scipy should be totally safe to run).

**Comment by ty-hei** [comment]
@Kukuster Thank you for your reply. I will close this issue, as I no longer use this tool for work reasons and do not intend to reproduce the problem. Thanks again!

**Comment by Kukuster** [comment]
@heihaheihaha Thank you for being responsive. It's a pity i wasn't able to provide support timely.
